# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "http://www.blueoxtavern.com"
languageCode = "en-US"
title = "Blue Ox Tavern"

# Metadata
[params]
  author = "The Aronsohn Family"
  description = "We'll Be Back"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "Blue Ox Tavern"
  description = "We'll Be Back"
